name: MinecartManiaAdminControls
main: com.afforess.minecartmaniaadmincontrols.MinecartManiaAdminControls
version: 1.1.4
author: Afforess
depend: [MinecartManiaCore]
commands:
  mm:
    description: Base MM command class
    usage: /<command>
  st:
    description: Sets the station value, for any station intersection the players may pass in a minecart
    usage: /<command>
  trucompass:
    description: Returns the true compass direction for the direction that the player is facing
    usage: /<command>
  throttle:
    description: Used in autocart to control the momentum of a minecart.
    usage: /<command> percent
  